### ISSUE TITLE
DivisionUndefined

### ISSUE THREAD

**Issue by guestl** [softandiron/tinkproject#10]
При первом же запуске выдало ошибку. 

Traceback (most recent call last):
  File "D:\tinkproject-main\main.py", line 248, in <module>
    my_positions = creating_positions_objects()
  File "D:\tinkproject-main\main.py", line 73, in creating_positions_objects
    percent_change = ((market_price / this_pos.average_position_price.value) * 100) - 100
decimal.InvalidOperation: [<class 'decimal.DivisionUndefined'>]

судя по всему, деление на ноль

я в 73 строке для отладки добавил вывод 
        # % change
        print(this_pos.average_position_price)
        print(this_pos.average_position_price.value)
        percent_change = ((market_price / this_pos.average_position_price.value) * 100) - 100

и он выдал следующее

Merck
currency=<Currency.usd: 'USD'> value=Decimal('0')
0

**Comment by guestl** [comment]
Дубль
