### ISSUE TITLE
При установке поверх без полного обновления зависимостей при запуске выдает ошибку

### ISSUE THREAD

**Issue by Igorjan666** [softandiron/tinkproject#22]
текст:
`INFO: 16:13:54 - creating operations objects..
Traceback (most recent call last):
  File "_путь_\tinkproject-main\main.py", line 396, in <module>
    my_operations = create_operations_objects()
  File "_путь_\tinkproject-main\main.py", line 249, in create_operations_objects
    instrument = data_parser.get_instrument_by_figi(this_op.figi)
  File "_путь_\tinkproject-main\data_parser.py", line 146, in get_instrument_by_figi
    instrument = client.get_market_search_by_figi(figi)
  File "_путь_\AppData\Local\Programs\Python\Python39\lib\site-packages\tinvest\clients.py", line 699, in get_market_search_by_figi
    return market_search_by_figi_get(
  File "_путь_\AppData\Local\Programs\Python\Python39\lib\site-packages\tinvest\apis.py", line 344, in market_search_by_figi_get
    return request(
  File "_путь_\AppData\Local\Programs\Python\Python39\lib\site-packages\tinvest\clients.py", line 535, in _request
    raise TooManyRequestsError
tinvest.exceptions.TooManyRequestsError`

после `pip install -r requirements.txt --upgrade` - всё нормально

**Comment by alexanderkmd** [comment]
Это проблема не обновлений, а частоты запросов к API.
Частично решается кэширование запросов (см. #28), что так же увеличивает скорость обработки в целом.

**Comment by evgkrsk** [comment]
Чтобы точно не было проблем с зависимостями - используйте воспроизводимые окружения, в данном случае докер-контейнер по приложенному Dockerfile.

Хотя тут конечно дело в лимите частоты запросов.
