### ISSUE TITLE
'SyncClient' object has no attribute 'get_accounts'

### ISSUE THREAD

**Issue by IntelOut** [softandiron/tinkproject#50]
Стало выводить такую ошибку.
```
[INFO] Parser: getting accounts
Traceback (most recent call last):
  File "main.py", line 448, in <module>
    accounts = data_parser.get_accounts()
  File "/home/ubuntu/tink/data_parser.py", line 81, in get_accounts
    accounts = client.get_accounts()
AttributeError: 'SyncClient' object has no attribute 'get_accounts'
```

**Comment by IntelOut** [comment]
nvm
