### ISSUE TITLE
API2: Ошибка при первом запуске, построении отчета 

### ISSUE THREAD

**Issue by chelishchev** [softandiron/tinkproject#63]
```
12:51:19 [DEBUG] root: Отношение цен - 1.000137797988149373019153920
12:51:21 [INFO] root: Royal Dutch Shell (A)
12:51:21 [DEBUG] Parser: Instrument for BBG00QPYJ5H0 found in DB
Traceback (most recent call last):
  File "/app/./main.py", line 479, in <module>
    my_positions = creating_positions_objects()
  File "/app/./main.py", line 138, in creating_positions_objects
    ave_buy_price_rub = calculate_ave_buy_price_rub(this_pos)
  File "/app/./main.py", line 96, in calculate_ave_buy_price_rub
    logger.warning('unknown currency in position: ' + this_pos.name)
AttributeError: 'PortfolioPosition' object has no attribute 'name'
```

**Comment by alexanderkmd** [comment]
Добрый день!

3 февраля произошло значимое обновление API до версии 1.0.0 
Я закинул изменения в скрипт (https://github.com/softandiron/tinkproject/commit/c253f4afb6ad94512c8ae4d03f22e0d5761d662a)

Просьба обновить скрипт и проверить работоспособность на данный момент.

**Comment by chelishchev** [comment]
@alexanderkmd не помогло, точно такая же ошибка

**Comment by alexanderkmd** [comment]
Могу я Вас попросить заменить 96 строку в файле `main.py` на следующую:

```
logger.warning(f'Unknown currency "{ops.currency}" in position: {this_pos.figi}')
```

И прислать вывод, который будет при этом. Легче будет без ключа дебага запускать.

**Comment by alexanderkmd** [comment]
> @alexanderkmd не помогло, точно такая же ошибка

@chelishchev 
Сделал частичный фикс проблемы - должен давать предупреждение, но не вылетать.
Убедительная просьба - текст предупреждения выложить сюда. Что-то с валютами - но отловить не могу.

**Comment by chelishchev** [comment]
@alexanderkmd да, помогло, прошло дальше.

`09:39:37 [WARNING] root: unknown currency "USD" in position: BBG00QPYJ5H0`
`09:39:39 [WARNING] root: unknown currency "USD" in position: BBG00QPYJ5H0`

**Comment by alexanderkmd** [comment]
@chelishchev Есть маленькое предложение - не могли бы вы дать мне временный read-only токен на ваш счет? У меня нет этих финансовых инструментов, и дебажить так - сложно :(
Написать можно в телеграмм "@alexanderk_md"
