### ISSUE TITLE
Ошибка Traceback (most recent call last):

### ISSUE THREAD

**Issue by jmnemonick123** [softandiron/tinkproject#9]
В самих файлах ничего не менялось, вставил токен и дату в файлик май аккаунт и всё

Как это выглядит:

```
getting account data..
account started: 2020 Aug 01
START
authorisation..
- authorisation success
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    positions, operations, market_rate_today_usd, market_rate_today_eur, currencies = data_parser.get_api_data()
  File "D:\tinkproject-main\tinkproject-main\data_parser.py", line 34, in get_api_data
    positions = client.get_portfolio()
AttributeError: 'SyncClient' object has no attribute 'get_portfolio'
```

**Comment by jmnemonick123** [comment]
Решено, была старая версия python. На 3.9 заработало.
